#!/usr/bin/env ruby

require 'rubygems'
require 'mechanize'
require 'dotenv/load'


agent = Mechanize.new do |agent|
  agent.user_agent_alias = 'Mac Safari'
end

agent.get('https://www.myfonts.com/secure/login/') do |login_page|
  # Login
  login_page.form_with(:id => 'signin_form') do |form|
    form.username = ENV['MYFONTS_USERNAME']
    form.password = ENV['MYFONTS_PASSWORD']
  end.click_button

  # Collect orders from order page
  orders_page = agent.get('https://www.myfonts.com/my/orders/') do |op|
    order_links = op.links_with(css: '.ordernumlink')
    total_orders = order_links.count
    order_links.each_with_index do |ol, idx|
      puts "Fetching #{idx + 1} of #{total_orders}..."
      order_number = ol.href.strip.gsub(/\//, '')
      file_name = File.join('downloads', "#{order_number}.zip")

      if File.exists?(file_name)
        puts "Skipping order #{order_number}.  File exists at #{file_name}"
        next
      end

      font_page = ol.click
      file_data = font_page.form_with(css: '.downloadallbtn form').click_button
      File.open(file_name, 'wb') << file_data.body
    end
  end
end
